### ISSUE TITLE
[Suggestion] Separate snapshots into the folders close to each story

### ISSUE THREAD

**Issue by xareelee** [storybooks/storyshots#84]
Currently, the `.snap` files generated by storyshots will be put in the `__snapshots__` folder where the `Storyshots.test.js` is.

```
snapshots/
  ┣━ Storyshots.test.js   // run for storyshots
  ┗━ __snapshots__       // current we put snapshots for storyshots in this folder
          ┗━ Storyshots.test.js.snap    // we should separate the snapshots to be close to the .stories file
```

This results in a huge `.snap` file with thousands lines of code. It's hard for code review. 

I think that the snapshots should be put in the  `__snapshots__` folder being close to the related `.stories`.

```
src/components/
  ┗━ SomeComponent   // for import
          ┣━ index.js                                // to export the component
          ┣━ SomeComponent.js              
          ┣━ SomeComponent.styles.js   
          ┣━ SomeComponent.stories.js  // Storybooks
          ┗━ __snapshots__                       // we should put .snap files here for storyshots
                 ┗━ Storyshots.test.js.snap // generated by Storyshots.test.js  (should put it here)
```

This will make code review easier. It's easy to know a change from which `.stories.js` file.

It would be better when we need to move the whole component folder into a separated module or project without losing its snapshots, doesn't it?

**Comment by olistic** [comment]
What do you guys think about having these two config options: `storyKindRegex` and `storyNameRegex` instead of the current `storyRegex`?

`storyNameRegex` would behave just as the existing `storyRegex`, while `storyKindRegex` would match against the story kind. This would give users the flexibility to do something like this:

```javascript
// SomeComponent.stories.js

// ...
storiesOf('SomeComponent', module)
    .add('foo', () => {
        // ...
    });
```

```javascript
// SomeComponent.test.js

import initStoryshots from 'storyshots';

initStoryshots({
  storyRegex: /^SomeComponent$/,
});
```

Which will cause storyshots (or jest actually) to output a `__snapshots__/` directory colocated with the component and with just its storyshots.

If you think it is a good idea, I'm happy to submit a PR!
